language: dart
with_content_shell: true
dart:
  - stable
  - dev
sudo: false
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: pub run pubtest:pubtestdependencies -p vm -p content-shell