version: 0.0.15
name: project_stable_test
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  pubtest:
    git:
      url: git://github.com/tekartik/pubtest.dart
      ref: dart2
    version: '>=0.3.0'
test_dependencies:
  - pubtest
#  - yacht
# - process_run
  - tekartik_common_utils
  - tekartik_test_menu
  - tekartik_pub
  - tekartik_mdl_js
# - fs_shim
# - sembast
# - dev_test
# - idb_shim
  - tekartik_sc
# - pubglobalupdate
# - synchronized
  - android_utils
  - io_utils
  - browser_utils
  - build_utils
dev_dependencies:
  test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'
dependency_overrides:
  tekartik_sc:
    git:
      url: git://github.com/tekartik/tekartik_sc.dart
      ref: dart2
  tekartik_pub:
    git:
      url: git://github.com/tekartik/tekartik_pub.dart
      ref: dart2
    version: '>=0.7.1'
#  idb_shim:
#    git: git://github.com/tekartik/idb_shim.dart
#  dev_test:
#    git: git://github.com/tekartik/dev_test.dart
#    version: '>=0.10.1'
#  sembast:
#    git: git://github.com/tekartik/sembast.dart
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
  tekartik_io_utils:
    git:
      url: git://github.com/tekartik/io_utils.dart
      ref: dart2
  tekartik_android_utils:
    git:
      url: git://github.com/tekartik/android_utils.dart
      ref: dart2
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
#  tekartik_mdl_js:
#    git:
#      url: git://github.com/tekartik/mdl_js.dart
#      ref: dart2
#  tekartik_test_menu:
#    git:
#      url: git://github.com/tekartik/test_menu.dart
#      ref: dart2
  yacht:
    git:
      url: git://github.com/tekartik/yacht.dart
      ref: dart2
#  pubglobalupdate:
#    git: git://github.com/tekartik/pubglobalupdate.dart
#  synchronized:
#    git: git://github.com/tekartik/synchronized.dart
  unscripted:
    hosted: unscripted
    version: any
  #pubtest:
  #  path: ../../tekartik/pubtest.dart
